### ISSUE TITLE
Create lesson team for XML lesson

### ISSUE THREAD

**Issue by libcce** [carpentries-incubator/lc-xml#3]
Hi @maneesha can you create a lesson team for the XML lesson and invite:

- [Catherine Smith](https://github.com/catsmith)
- [Jesse Johnston](https://github.com/morskyjezek)
- [Phil Reed](https://github.com/PhilReedData)
- [Katrina Simone Fenlon](https://github.com/kfenlon)
- [Nilani Ganeshwaran](https://github.com/uom-nilani)

Thank you!

**Comment by maneesha** [comment]
I am reviewing some super old issues.  @libcce  Is this still needed?

**Comment by libcce** [comment]
@PhilReedData @morskyjezek @catsmith @kfenlon @uom-nilani my understanding is that the XML lesson never picked up enough steam to move forward. Should we close this lesson repo? @PhilReedData you spoke of a lesson in the incubator, maybe similar to this lesson?

**Comment by catsmith** [comment]
I can't see that I will be in a position to make any significant contributions to this for the next few years so I would not mind if this was closed. I am sorry about that because I think it would be a good addition to the carpentries family but it is a realistic assessment of my current work load.

**Comment by PhilReedData** [comment]
Hi @libcce, here is the [incubator lesson for TEI XML](https://github.com/carpentries-incubator/tei-xml), still hoping to get this moving along some time. Yes, I think this LC XML should be closed now, sadly. It was a pleasure working with you all, let's keep in touch, and, if you are interested in the TEI lesson, please let me know.

**Comment by maneesha** [comment]
I'm closing this issue.  You can always re-open this or start a new issue if you want to revisit it.  Thanks!

**Comment by morskyjezek** [comment]
Thanks, all. Maybe this can be picked up or replaced by the TEI lesson. As @libcce said, I think we just never got the momentum going on this.

**Comment by libcce** [comment]
@morskyjezek that would be great... @PhilReedData I may have heard this wrong but you were considering the TEI lesson to live in Data Carpentry instead? Would be great if it could live in LC and we can actually move your lesson to start getting more attention/contributions? 3 people on the maintainer list responded but it would be great if the rest of our maintiners listed can respond?
